#!/bin/bash
nvim $(fzf --layout reverse --info inline --border --preview 'file {}' --preview-window up,1,border-horizontal --color 'fg:#bbccdd,fg+:#ddeeff,bg:#334455,preview-bg:#223344,border:#778899' -m)
